# Generated by Django 6.0.1 on 2026-03-14 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Human-readable order number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Items total', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Tax amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_cost', models.DecimalField(decimal_places=2, help_text='Shipping fee', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Total discount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final total', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(db_index=True, default='USD', help_text='Currency code', max_length=3)),
                ('notes', models.TextField(blank=True, help_text='Customer notes', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Customer IP', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser info', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Order creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last status update')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Payment timestamp', null=True)),
                ('shipped_at', models.DateTimeField(blank=True, help_text='Shipping timestamp', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Delivery timestamp', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Cancellation timestamp', null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], max_length=20)),
                ('full_name', models.CharField(help_text='Recipient name', max_length=200)),
                ('phone_number', models.CharField(help_text='Contact phone', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\s*\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$', 'Enter valid phone number')])),
                ('address_line_1', models.CharField(help_text='Street address', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, etc.', max_length=255, null=True)),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('state_province', models.CharField(help_text='State/Province', max_length=100)),
                ('postal_code', models.CharField(help_text='ZIP/Postal code', max_length=100)),
                ('country', models.CharField(help_text='Country name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order Address',
                'verbose_name_plural': 'Order Addresses',
                'db_table': 'order_addresses',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name at purchase', max_length=255)),
                ('variant_name', models.CharField(blank=True, help_text='Variant details', max_length=255, null=True)),
                ('sku', models.CharField(help_text='SKU at purchase', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Ordered quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Quantity x unit_price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Item discount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax for this item', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, help_text='Final item total', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
                'db_table': 'order_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, help_text='Tracking number', max_length=100, null=True)),
                ('carrier', models.CharField(blank=True, help_text='Shipping carrier', max_length=100, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, help_text='Ship date', null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, help_text='Estimated arrival', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Actual delivery date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Shipping',
                'verbose_name_plural': 'Order Shipping',
                'db_table': 'order_shipping',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Method name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Method description', null=True)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Shipping cost', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_days_min', models.PositiveIntegerField(blank=True, help_text='Min delivery days', null=True, validators=[django.core.validators.MaxValueValidator(365)])),
                ('estimated_days_max', models.PositiveIntegerField(blank=True, help_text='Max delivery days', null=True, validators=[django.core.validators.MaxValueValidator(365)])),
                ('is_active', models.BooleanField(default=True, help_text='Active status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'db_table': 'shipping_methods',
            },
        ),
    ]
