services:
  backend:
    build: .
    ports:
      - "8000:8000"

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: cartiz
      POSTGRES_USER: cartiz_user
      POSTGRES_PASSWORD: cartiz_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: