# Generated by Django 6.0.1 on 2026-03-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, help_text='Message subject', max_length=255, null=True)),
                ('message', models.TextField(help_text='Message content')),
                ('is_read', models.BooleanField(default=False, help_text='Read status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Send timestamp')),
                ('read_at', models.DateTimeField(blank=True, help_text='Read timestamp', null=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('message', 'Message'), ('review', 'Review'), ('promotion', 'Promotion')], max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification content')),
                ('link', models.URLField(blank=True, help_text='Related link/URL', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Read status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('read_at', models.DateTimeField(blank=True, help_text='When marked as read', null=True)),
            ],
            options={
                'verbose_name': 'Notifications',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(help_text='Ticket reference', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('order_issue', 'Order Issue'), ('payment', 'Payment'), ('product', 'Product'), ('account', 'Account'), ('other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('subject', models.CharField(help_text='Ticket subject', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Issue description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ticket creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Resolution time', null=True)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Reply content')),
                ('is_staff_reply', models.BooleanField(default=False, help_text='Staff vs customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Support Ticket Reply',
                'verbose_name_plural': 'Support Ticket Replies',
                'db_table': 'support_ticket_replies',
                'ordering': ['created_at'],
            },
        ),
    ]
