# Generated by Django 6.0.1 on 2026-03-14 15:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Coupon code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Coupon description', null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount amount/percentage', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order value', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount cap', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total usage limit', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Times used')),
                ('per_user_limit', models.PositiveIntegerField(default=1, help_text='Uses per user')),
                ('valid_from', models.DateTimeField(help_text='Start date')),
                ('valid_until', models.DateTimeField(help_text='End date')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='stores.market')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Discount applied', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('used_at', models.DateTimeField(auto_now_add=True, help_text='Usage timestamp')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='promotions.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'db_table': 'coupon_usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupons_code_94ae53_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['market'], name='coupons_market__f092c7_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='coupons_is_acti_dbb3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_until'], name='coupons_valid_u_bf1c18_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon'], name='coupon_usag_coupon__f4b516_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['user'], name='coupon_usag_user_id_1c3309_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user'], name='coupon_usag_coupon__4d4fe8_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.UniqueConstraint(fields=('coupon', 'order'), name='unique_coupon_usage_per_order'),
        ),
    ]
