# Generated by Django 6.0.1 on 2026-05-28 13:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('promotions', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Percentage discount applied to all sale products', max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='stores.market')),
                ('products', models.ManyToManyField(blank=True, related_name='flash_sales', to='products.product')),
            ],
            options={
                'verbose_name': 'Flash Sale',
                'verbose_name_plural': 'Flash Sales',
                'db_table': 'flash_sales',
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['is_active'], name='flash_sales_is_acti_16fa7b_idx'), models.Index(fields=['starts_at', 'ends_at'], name='flash_sales_starts__c8e92e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('promo_type', models.CharField(choices=[('banner', 'Banner'), ('discount', 'Discount'), ('bundle', 'Bundle'), ('seasonal', 'Seasonal'), ('clearance', 'Clearance')], default='discount', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='stores.market')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='products.product')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'promotions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='promotions_is_acti_5031c3_idx'), models.Index(fields=['promo_type'], name='promotions_promo_t_019953_idx'), models.Index(fields=['starts_at', 'ends_at'], name='promotions_starts__d30377_idx')],
            },
        ),
    ]
