# Generated by Django 6.0.1 on 2026-03-14 15:24

import apps.payments.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Internal transaction ID', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Card')], default='card', help_text='Payment method', max_length=50)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failure', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Payment attempt time')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Success timestamp', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Card number', max_length=19, validators=[django.core.validators.RegexValidator('^\\d{13,19}$', 'Enter a valid card number')])),
                ('card_holder_name', models.CharField(help_text='Card Holder Name', max_length=200, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:'[A-Za-z]+)?(?: [A-Za-z]+(?:'[A-Za-z]+)?)*$", 'Enter valid name')])),
                ('expiry_month', models.IntegerField(help_text='Expiration month', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expiry_year', models.IntegerField(help_text='Expiration year', validators=[django.core.validators.MinValueValidator(apps.payments.models.current_year)])),
                ('cvv', models.CharField(help_text='Card CVV code', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{3,4}$', 'Enter Valid CVV')])),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Card Balance', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Card',
                'verbose_name_plural': 'User Cards',
                'db_table': 'user_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(editable=False, help_text='Refund reference number', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField(blank=True, help_text='Reason for refund', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Refund status', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='payments.usercard')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'db_table': 'refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.usercard'),
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('payment', 'Payment'), ('transfer', 'Transfer'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.usercard')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'card_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usercard',
            index=models.Index(fields=['user'], name='user_cards_user_id_0ff464_idx'),
        ),
        migrations.AddIndex(
            model_name='usercard',
            index=models.Index(fields=['card_number'], name='user_cards_card_nu_8150e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_card_per_user'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order'], name='refunds_order_i_20e1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='refunds_status_2569d8_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['created_at'], name='refunds_created_7e4196_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payments_order_i_b32b33_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_created_e3a130_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed')), fields=('order',), name='one_completed_payment_per_order'),
        ),
        migrations.AddIndex(
            model_name='cardtransaction',
            index=models.Index(fields=['card'], name='card_transa_card_id_6c9f78_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtransaction',
            index=models.Index(fields=['created_at'], name='card_transa_created_686faf_idx'),
        ),
    ]
