# Generated by Django 6.0.1 on 2026-03-14 15:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(help_text='Store name', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$', 'Enter valid name')])),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, help_text='Store description', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Store logo image', null=True, upload_to='seller/market/logos/')),
                ('banner_image', models.ImageField(blank=True, help_text='Store banner image', null=True, upload_to='seller/market/banners/')),
                ('business_email', models.EmailField(blank=True, help_text='Business contact email', max_length=254, null=True)),
                ('business_phone', models.CharField(help_text='Business phone number', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\s*\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$', 'Enter valid phone number')])),
                ('business_address', models.TextField(blank=True, help_text='Physical store address', null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Business tax ID', max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified seller status')),
                ('is_active', models.BooleanField(default=True, help_text='Store active status')),
                ('rating_average', models.DecimalField(decimal_places=2, default=0, help_text='Average rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_sales', models.PositiveIntegerField(help_text='Total number of sales')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Store creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
                'db_table': 'markets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Star rating (1-5)', max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Review text', null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Moderation status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Review submission time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last edit time')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.market')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market Review',
                'verbose_name_plural': 'Market Reviews',
                'db_table': 'market_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['slug'], name='markets_slug_213148_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['seller'], name='markets_seller__9494e4_idx'),
        ),
        migrations.AddIndex(
            model_name='marketreview',
            index=models.Index(fields=['market'], name='market_revi_market__1ff05b_idx'),
        ),
        migrations.AddIndex(
            model_name='marketreview',
            index=models.Index(fields=['is_approved'], name='market_revi_is_appr_1f85c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketreview',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_market_review'),
        ),
    ]
